apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: my-app  # Use the namespace if created
spec:
  replicas: 1  # Adjust based on your needs
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: mohamedelrefy20/backend  # Replace with your backend image or build it
        ports:
        - containerPort: 5000
---
