version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Expose the React app on port 3000
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://backend:5000  # Point to the backend service
    networks:
      - my-network

  backend:
    build:
      context: ./backend/src
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Expose the Flask app on port 5000
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
