version: '3.8'

services:
  backend:
    build:
      context: ./backend/src
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000  
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}  ##
    volumes:
      - .:/app   
    ports:
      - "5000:8000"  # Expose the Flask app on port 8000
    networks:
      - my-network

  frontend:
    build:
      context: ./react-frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"  # Expose the React app on port 
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://backend:8000  # Point to the backend service
    networks:
      - my-network
    

networks:
  my-network:
    driver: bridge
