---
  - name: Install Jenkins on agent1
    hosts: agent1  # Replace with your target host or group
    become: yes    # Use become to execute tasks with sudo privileges
    vars:
      jenkins: jenkins 
      jenkins_url: http://192.168.1.3:8080  # Define Jenkins URL
      jenkins_username: mohamed_elrefy  # Define Jenkins username
      jenkins_api_token: slack_token # Replace with your Jenkins API token
    
    tasks: 
      
  
      - name: Install required packages
        apt:
          name:
            - openjdk-11-jdk  # Install OpenJDK 11
            - docker.io
            - git #git install
            - curl
            - docker-compose
            - python3-pip  # Optional, for any Python-based tasks
          state: present
  
      - name: Ensure Docker service is running
        service:
          name: docker
          state: started
          enabled: yes
  
      - name: Add user to docker group
        user:
          name: "{{ jenkins }}"  # Replace with your Jenkins user if needed
          group: docker
          append: yes
  
      - name: Install Jenkins agent (if needed)
        shell: |
          curl -O http://updates.jenkins-ci.org/download/plugins/swarm-client/3.21/swarm-client.jar
          mv swarm-client.jar /usr/local/bin/jenkins-swarm-client.jar
  
      - name: Create Jenkins swarm agent startup script
        copy:
          dest: /usr/local/bin/start-jenkins-agent.sh
          content: |
            #!/bin/bash
            java -jar /usr/local/bin/jenkins-swarm-client.jar -master http://192.168.1.3:8080 -username mohamed_elrefy -password beboXbebo@123 -executors 1 -name {{ inventory_hostname }}
  
      - name: Make startup script executable
        file:
          path: /usr/local/bin/start-jenkins-agent.sh
          mode: '0755'
  
      - name: Create systemd service for Jenkins agent
        copy:
          dest: /etc/systemd/system/jenkins-agent.service
          content: |
            [Unit]
            Description=Jenkins Agent
  
            [Service]
            ExecStart=/usr/local/bin/start-jenkins-agent.sh
            Restart=always
  
            [Install]
            WantedBy=multi-user.target
  
      - name: Enable and start Jenkins agent service
        systemd:
          name: jenkins-agent
          state: started
          enabled: yes
  
      
  
  