apiVersion: v1
kind: Secret
metadata:
  name: openai-api-secret
  namespace: my-app
type: Opaque #type
data:
  OPENAI_API_KEY: c2stcHJvai03ODRxOE9PY3M4Mzc2VDNGWlh4ZnNYdy1CNW1KNldQSGZ5WmlkaDM2UER2UUo1RHk0cmZzeFNJcUt3Z3k4R0YyRHhuQXUwOXVoTFQzQmxia0ZKS0NuMDRxMkd4SUUzaERnM3haVVN4LWpKQ3dLRGNqdWIyNzhvc3V1YVVsODBnOG9vLUFDRlBSSEZ2WGRyUFRoQzFSVTNVWElpRUE=
